-- RETURNS NULL FOR EMPTY STRING
CREATE OR REPLACE FUNCTION GET_NULL(PARAM IN VARCHAR2)
RETURN VARCHAR2 IS
BEGIN
    IF PARAM = '' THEN
        RETURN NULL;
    end if;

    RETURN PARAM;
END;




-- SEARCH THE ADDRESS_ID, IF NONE THEN CREATE NEW ADDRESS
CREATE OR REPLACE FUNCTION GET_ADD_ID(
    STREET IN VARCHAR2,
    CITY_NAME IN VARCHAR2,
    POST IN VARCHAR2,
    SUB IN VARCHAR2,
    DIS IN VARCHAR2
)
RETURN NUMBER IS
    ID NUMBER;
BEGIN
    ID := -1;

    -- Using INTO clause to assign the selected value to the ID variable
    SELECT A.ADDRESS_ID INTO ID
    FROM ADDRESS A
    WHERE A.STREET_ADDRESS = STREET
    AND A.CITY = CITY_NAME
    AND A.POSTAL_CODE = POST;

    RETURN ID;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ID = '|| ID);


        SELECT MAX(ADDRESS_ID) INTO ID
        FROM ADDRESS;
        -- UNIQUE IN FOR NEW ADDRESS
        ID := ID + 1;
        DBMS_OUTPUT.PUT_LINE(ID);
        -- INSERT NEW ADDRESS
        INSERT INTO ADDRESS
        (ADDRESS_ID, STREET_ADDRESS, CITY, POSTAL_CODE, SUB_DISTRICT, DISTRICT)
        VALUES
        (ID, STREET, CITY_NAME, POST, SUB, DIS);

        RETURN ID;
END;
