-- trigger
CREATE OR REPLACE TRIGGER DELETE_FUTURE_APPOINTMENT
AFTER INSERT
ON PAST_APPOINTMENT
FOR EACH ROW
BEGIN
    DELETE FROM FUTURE_APPOINTMENT FA
    WHERE FA.PATIENT_ID = :NEW.PATIENT_ID
    AND FA.DOCTOR_ID = :NEW.DOCTOR_ID
    AND TO_CHAR(FA.APPOINTMENT_DATE) = TO_CHAR(:NEW.APPOINTMENT_DATE);
END;
/