-- trigger
CREATE OR REPLACE TRIGGER DELETE_FUTURE_APPOINTMENT
AFTER INSERT
ON PAST_APPOINTMENT
FOR EACH ROW
BEGIN
    DELETE FROM FUTURE_APPOINTMENT FA
    WHERE FA.PATIENT_ID = :NEW.PATIENT_ID
    AND FA.DOCTOR_ID = :NEW.DOCTOR_ID
    AND TO_CHAR(FA.APPOINTMENT_DATE) = TO_CHAR(:NEW.APPOINTMENT_DATE);
END;
/



CREATE OR REPLACE TRIGGER DEFAULT_IMAGE
BEFORE INSERT
ON PATIENT
FOR EACH ROW
BEGIN
 IF :NEW.PHOTO_URL IS NULL THEN
	:NEW.PHOTO_URL := 'https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg';
END IF;

END;

/